import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Header = () => (
  <header style={{ padding: "1rem", background: "#f5f5f5" }}>
    <h1>My App</h1>
  </header>
);

const Footer = () => (
  <footer style={{ padding: "1rem", background: "#f5f5f5", marginTop: "2rem" }}>
    <p>&copy; 2025 My App. All rights reserved.</p>
  </footer>
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Header />
      <main>{children}</main>
      <Footer />
    </html>
  );
}
